// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/proto/pack.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilenameHash  string                 `protobuf:"bytes,1,opt,name=filename_hash,json=filenameHash,proto3" json:"filename_hash,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_internal_proto_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_pack_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFilenameHash() string {
	if x != nil {
		return x.FilenameHash
	}
	return ""
}

func (x *FileInfo) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileInfos     []*FileInfo            `protobuf:"bytes,1,rep,name=file_infos,json=fileInfos,proto3" json:"file_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackInfo) Reset() {
	*x = PackInfo{}
	mi := &file_internal_proto_pack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackInfo) ProtoMessage() {}

func (x *PackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackInfo.ProtoReflect.Descriptor instead.
func (*PackInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_pack_proto_rawDescGZIP(), []int{1}
}

func (x *PackInfo) GetFileInfos() []*FileInfo {
	if x != nil {
		return x.FileInfos
	}
	return nil
}

var File_internal_proto_pack_proto protoreflect.FileDescriptor

const file_internal_proto_pack_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/pack.proto\"[\n" +
	"\bFileInfo\x12#\n" +
	"\rfilename_hash\x18\x01 \x01(\tR\ffilenameHash\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"4\n" +
	"\bPackInfo\x12(\n" +
	"\n" +
	"file_infos\x18\x01 \x03(\v2\t.FileInfoR\tfileInfosB\rZ\v./;protocolb\x06proto3"

var (
	file_internal_proto_pack_proto_rawDescOnce sync.Once
	file_internal_proto_pack_proto_rawDescData []byte
)

func file_internal_proto_pack_proto_rawDescGZIP() []byte {
	file_internal_proto_pack_proto_rawDescOnce.Do(func() {
		file_internal_proto_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_pack_proto_rawDesc), len(file_internal_proto_pack_proto_rawDesc)))
	})
	return file_internal_proto_pack_proto_rawDescData
}

var file_internal_proto_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_pack_proto_goTypes = []any{
	(*FileInfo)(nil), // 0: FileInfo
	(*PackInfo)(nil), // 1: PackInfo
}
var file_internal_proto_pack_proto_depIdxs = []int32{
	0, // 0: PackInfo.file_infos:type_name -> FileInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_pack_proto_init() }
func file_internal_proto_pack_proto_init() {
	if File_internal_proto_pack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_pack_proto_rawDesc), len(file_internal_proto_pack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_pack_proto_goTypes,
		DependencyIndexes: file_internal_proto_pack_proto_depIdxs,
		MessageInfos:      file_internal_proto_pack_proto_msgTypes,
	}.Build()
	File_internal_proto_pack_proto = out.File
	file_internal_proto_pack_proto_goTypes = nil
	file_internal_proto_pack_proto_depIdxs = nil
}
