// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/proto/wal.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLog) Reset() {
	*x = FileLog{}
	mi := &file_internal_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLog) ProtoMessage() {}

func (x *FileLog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLog.ProtoReflect.Descriptor instead.
func (*FileLog) Descriptor() ([]byte, []int) {
	return file_internal_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *FileLog) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WAL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*FileLog             `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WAL) Reset() {
	*x = WAL{}
	mi := &file_internal_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WAL) ProtoMessage() {}

func (x *WAL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WAL.ProtoReflect.Descriptor instead.
func (*WAL) Descriptor() ([]byte, []int) {
	return file_internal_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *WAL) GetLogs() []*FileLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_internal_proto_wal_proto protoreflect.FileDescriptor

const file_internal_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/wal.proto\"9\n" +
	"\aFileLog\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"#\n" +
	"\x03WAL\x12\x1c\n" +
	"\x04logs\x18\x01 \x03(\v2\b.FileLogR\x04logsB\rZ\v./;protocolb\x06proto3"

var (
	file_internal_proto_wal_proto_rawDescOnce sync.Once
	file_internal_proto_wal_proto_rawDescData []byte
)

func file_internal_proto_wal_proto_rawDescGZIP() []byte {
	file_internal_proto_wal_proto_rawDescOnce.Do(func() {
		file_internal_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_wal_proto_rawDesc), len(file_internal_proto_wal_proto_rawDesc)))
	})
	return file_internal_proto_wal_proto_rawDescData
}

var file_internal_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_wal_proto_goTypes = []any{
	(*FileLog)(nil), // 0: FileLog
	(*WAL)(nil),     // 1: WAL
}
var file_internal_proto_wal_proto_depIdxs = []int32{
	0, // 0: WAL.logs:type_name -> FileLog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_wal_proto_init() }
func file_internal_proto_wal_proto_init() {
	if File_internal_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_wal_proto_rawDesc), len(file_internal_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_wal_proto_goTypes,
		DependencyIndexes: file_internal_proto_wal_proto_depIdxs,
		MessageInfos:      file_internal_proto_wal_proto_msgTypes,
	}.Build()
	File_internal_proto_wal_proto = out.File
	file_internal_proto_wal_proto_goTypes = nil
	file_internal_proto_wal_proto_depIdxs = nil
}
